version: '3'

networks:
  webapps:
    external: true
  catalog:
  cart:
  order:
  inventory:
  gateway:
  rabbitmq:

services:
  gateway:
    image: redbeandock/polyshop-gateway:latest
    restart: always
    hostname: polyshop_gateway
    depends_on:
      - catalog
      - cart
      - order
      - inventory
    env_file:
      - gateway.env
    networks:
      - webapps
      - gateway
  
  rabbitmq:
    image: rabbitmq:management
    restart: always
    env_file:
      - rabbitmq.env
    networks:
      - rabbitmq

  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - postgres.env
    networks:
      - order
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  eventstore_order:
    image: eventstore/eventstore:21.10.1-buster-slim
    restart: always
    env_file:
      - eventstore_order.env
    networks:
      - order
    volumes:
      - ./eventstore-order-data:/var/lib/eventstore
      - ./eventstore-order-logs:/var/log/eventstore
  
  mongo_catalog:
    image: mongo:6.0.5
    restart: always
    env_file:
      - mongo_catalog.env
    networks:
      - catalog
    volumes:
      - ./mongo-catalog-data:/data/db

  redis:
    image: redis:7.0.9
    restart: always
    env_file:
      - redis.env
    networks:
      - cart

  mongo_inventory:
    image: mongo:6.0.5
    restart: always
    env_file:
      - mongo_inventory.env
    networks:
      - inventory
    volumes:
      - ./mongo-inventory-data:/data/db

  catalog:
    image: redbeandock/polyshop-catalog:latest
    restart: always
    hostname: polyshop_catalog
    depends_on:
      - mongo_catalog
      - rabbitmq
    env_file:
      - catalog.env
    networks:
      - catalog
      - rabbitmq
      - gateway
  
  cart:
    image: redbeandock/polyshop-cart:latest
    restart: always
    hostname: polyshop_cart
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - cart.env
    networks:
      - cart
      - rabbitmq
      - gateway

  order:
    image: redbeandock/polyshop-order:latest
    restart: always
    hostname: polyshop_order
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - order.env
    networks:
      - order
      - rabbitmq
      - gateway

  inventory:
    image: redbeandock/polyshop-inventory:latest
    restart: always
    hostname: polyshop_inventory
    depends_on:
      - mongo_inventory
      - rabbitmq
    env_file:
      - inventory.env
    networks:
      - inventory
      - rabbitmq
      - gateway

  payment:
    image: redbeandock/polyshop-payment:latest
    restart: always
    hostname: polyshop_payment
    depends_on:
      - rabbitmq
    env_file:
      - payment.env
    networks:
      - rabbitmq
      - gateway

  shipping:
    image: redbeandock/polyshop-shipping:latest
    restart: always
    hostname: polyshop_shipping
    depends_on:
      - rabbitmq
    env_file:
      - shipping.env
    networks:
      - rabbitmq
      - gateway
  
  frontend:
    image: redbeandock/polyshop-frontend:latest
    restart: always
    hostname: polyshop_frontend
    depends_on:
      - gateway
    env_file:
      - frontend.env
    networks:
      - gateway
      - webapps